import PlaygroundSupport
import TortoiseGraphics
import CoreGraphics

let canvas = PlaygroundCanvas(frame: CGRect(x: 0, y: 0, width: 500, height: 500))
canvas.frameRate = 300
canvas.color = .white
PlaygroundPage.current.liveView = canvas

canvas.drawing { turtle in
    turtle.hideTortoise()
   
//draw circle
    turtle.penColor(.red)
    turtle.penSize(7)
    turtle.penUp()
    turtle.goto(-240,185)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(125)
    turtle.forward(55)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(55)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(40)
    
    //draw circle
    turtle.penColor(.black)
    turtle.penSize(7)
    turtle.penUp()
    turtle.goto(-30,175)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(125)
    turtle.forward(55)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(55)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(40)
    
    //draw circle
    turtle.penColor(.red)
    turtle.penSize(7)
    turtle.penUp()
    turtle.goto(-100,10)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(125)
    turtle.forward(55)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(55)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(40)
    
    //draw circle
    turtle.penColor(.black)
    turtle.penSize(7)
    turtle.penUp()
    turtle.goto(130,125)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(125)
    turtle.forward(55)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(55)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(40)
    
    //draw circle
    turtle.penColor(.red)
    turtle.penSize(7)
    turtle.penUp()
    turtle.goto(10,5)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(125)
    turtle.forward(55)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(55)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(40)
  
    //draw circle
    turtle.penColor(.black)
    turtle.penSize(7)
    turtle.penUp()
    turtle.goto(100,35)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(125)
    turtle.forward(55)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(55)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(40)
    
    //draw circle
    turtle.penColor(.red)
    turtle.penSize(7)
    turtle.penUp()
    turtle.goto(-230,-175)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(125)
    turtle.forward(55)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(55)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(40)
    
    //draw circle
    turtle.penColor(.red)
    turtle.penSize(7)
    turtle.penUp()
    turtle.goto(-40,-145)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(125)
    turtle.forward(55)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(55)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(40)
   
    //draw circle
    turtle.penColor(.red)
    turtle.penSize(7)
    turtle.penUp()
    turtle.goto(130,-155)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(125)
    turtle.forward(55)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(55)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(40)
    
    //draw circle
    turtle.penColor(.black)
    turtle.penSize(7)
    turtle.penUp()
    turtle.goto(150,-85)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(125)
    turtle.forward(55)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(55)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(40)
    
    //draw circle
    turtle.penColor(.red)
    turtle.penSize(7)
    turtle.penUp()
    turtle.goto(160,-155)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(125)
    turtle.forward(55)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(55)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(40)
    
    //draw circle
    turtle.penColor(.black)
    turtle.penSize(7)
    turtle.penUp()
    turtle.goto(110,205)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(125)
    turtle.forward(55)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(55)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(40)
    
    //draw circle
    turtle.penColor(.black)
    turtle.penSize(7)
    turtle.penUp()
    turtle.goto(-100,-145)
    turtle.penDown()
    turtle.curve(withSides: 15, withSize: 20, drawSides: 15)
    turtle.right(90)
    turtle.forward(95)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(45)
    turtle.penDown()
    turtle.right(125)
    turtle.forward(55)
    turtle.right(180)
    turtle.penUp()
    turtle.forward(55)
    turtle.penDown()
    turtle.left(100)
    turtle.forward(40)
 turtle.hideTortoise()
}
