: # With a tortoise 🐢
: [👉 With 2 tortoises 🐢🐢](@next)
/*

import PlaygroundSupport
import TortoiseGraphics
import CoreGraphics
let myFrame = CGRect(x: 0, y: 0, width: 500, height: 500)
let canvas = PlaygroundCanvas(frame: myFrame)
canvas.frameRate = 30
canvas.color = .white
PlaygroundPage.current.liveView = canvas

canvas.drawing { turtle in
    turtle.penUp()
    turtle.goto(-250,-250)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(-200,-250)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(-150,-250)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(-100,-250)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(-50,-250)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(50,-250)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(100,-250)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(150,-250)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(200,-250)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(250,-250)
    turtle.penDown()
    turtle.forward(500)
    turtle.left(90)
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(250,200)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(250,150)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(250,100)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(250,50)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(250,-50)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(250,-100)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(250,-150)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(250,-200)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(250,-250)
    turtle.penDown()
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(0,-250)
    turtle.penDown()
    turtle.right(90)
    turtle.forward(500)
    turtle.right(180)
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(250,0)
    turtle.penDown()
    turtle.right(90)
    turtle.forward(500)
    turtle.left(180)
    turtle.forward(500)
    turtle.penUp()
    turtle.goto(0,0)
    turtle.penDown()
    turtle.left(90)
 
 
 
 
 
}

*/
